//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameClient_12._01._2020.ServiceReferenceMD5 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceMD5.IServiceMD5")]
    public interface IServiceMD5 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMD5/GetMd5Hash", ReplyAction="http://tempuri.org/IServiceMD5/GetMd5HashResponse")]
        string GetMd5Hash(string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMD5/GetMd5Hash", ReplyAction="http://tempuri.org/IServiceMD5/GetMd5HashResponse")]
        System.Threading.Tasks.Task<string> GetMd5HashAsync(string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMD5/GetMd5HashWithMD5Hash", ReplyAction="http://tempuri.org/IServiceMD5/GetMd5HashWithMD5HashResponse")]
        string GetMd5HashWithMD5Hash(System.Security.Cryptography.MD5 md5Hash, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMD5/GetMd5HashWithMD5Hash", ReplyAction="http://tempuri.org/IServiceMD5/GetMd5HashWithMD5HashResponse")]
        System.Threading.Tasks.Task<string> GetMd5HashWithMD5HashAsync(System.Security.Cryptography.MD5 md5Hash, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMD5/VerifyMd5Hash", ReplyAction="http://tempuri.org/IServiceMD5/VerifyMd5HashResponse")]
        bool VerifyMd5Hash(string password, string hashedPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMD5/VerifyMd5Hash", ReplyAction="http://tempuri.org/IServiceMD5/VerifyMd5HashResponse")]
        System.Threading.Tasks.Task<bool> VerifyMd5HashAsync(string password, string hashedPassword);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceMD5Channel : GameClient_12._01._2020.ServiceReferenceMD5.IServiceMD5, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceMD5Client : System.ServiceModel.ClientBase<GameClient_12._01._2020.ServiceReferenceMD5.IServiceMD5>, GameClient_12._01._2020.ServiceReferenceMD5.IServiceMD5 {
        
        public ServiceMD5Client() {
        }
        
        public ServiceMD5Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceMD5Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceMD5Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceMD5Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetMd5Hash(string password) {
            return base.Channel.GetMd5Hash(password);
        }
        
        public System.Threading.Tasks.Task<string> GetMd5HashAsync(string password) {
            return base.Channel.GetMd5HashAsync(password);
        }
        
        public string GetMd5HashWithMD5Hash(System.Security.Cryptography.MD5 md5Hash, string password) {
            return base.Channel.GetMd5HashWithMD5Hash(md5Hash, password);
        }
        
        public System.Threading.Tasks.Task<string> GetMd5HashWithMD5HashAsync(System.Security.Cryptography.MD5 md5Hash, string password) {
            return base.Channel.GetMd5HashWithMD5HashAsync(md5Hash, password);
        }
        
        public bool VerifyMd5Hash(string password, string hashedPassword) {
            return base.Channel.VerifyMd5Hash(password, hashedPassword);
        }
        
        public System.Threading.Tasks.Task<bool> VerifyMd5HashAsync(string password, string hashedPassword) {
            return base.Channel.VerifyMd5HashAsync(password, hashedPassword);
        }
    }
}
